name: CI Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:TreatWarningsAsErrors=true
      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Check formatting using csharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .
